media: media/uploads # 指定图片/视频上传的目标文件夹

content:
  - name: docs
    label: 文章管理
    type: collection
    path: source # 管理 content 目录下的文件
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 内容
        type: rich-text