name: Auto Save to Wayback Machine
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '00 1 * * *'  # 北京时间 08:51

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Save to Wayback Machine
        uses: JamieMagee/wayback@v2
        with:
          url: https://senchin.dpdns.org
