name: Package Repository ZIP & Upload to Release
run-name: Package and Upload to Release
on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date in yyyy‑mm‑dd format
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download master branch ZIP
        run: wget https://github.com/${{ github.repository }}/archive/refs/heads/master.zip -O ${{ env.DATE }}.zip

      - name: Update Backup Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Backup
          name: Daily Backup ${{ env.DATE }}
          files: ${{ env.DATE }}.zip
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
